export interface Brand {
  id: string;
  name: string;
  country: string;
  segment: 'budget' | 'premium' | 'luxury' | 'sports';
  modelCount: number;
  founded: string;
  tagline: string;
  accentColor: string;
}

export const brands: Brand[] = [
  {
    id: 'honda',
    name: 'Honda',
    country: '🇯🇵 Japan',
    segment: 'premium',
    modelCount: 2,
    founded: '1948',
    tagline: 'The Power of Dreams',
    accentColor: '#CC0000',
  },
  {
    id: 'mahindra',
    name: 'Mahindra',
    country: '🇮🇳 India',
    segment: 'budget',
    modelCount: 1,
    founded: '1945',
    tagline: 'Rise',
    accentColor: '#CC0000',
  },
  {
    id: 'toyota',
    name: 'Toyota',
    country: '🇯🇵 Japan',
    segment: 'premium',
    modelCount: 2,
    founded: '1937',
    tagline: 'Let\'s Go Places',
    accentColor: '#EB0A1E',
  },
  {
    id: 'maruti',
    name: 'Maruti',
    country: '🇮🇳 India',
    segment: 'budget',
    modelCount: 2,
    founded: '1981',
    tagline: 'Way of Life',
    accentColor: '#0066CC',
  },
  {
    id: 'hyundai',
    name: 'Hyundai',
    country: '🇰🇷 Korea',
    segment: 'premium',
    modelCount: 2,
    founded: '1967',
    tagline: 'New Thinking, New Possibilities',
    accentColor: '#002C5F',
  },
  {
    id: 'tata',
    name: 'Tata',
    country: '🇮🇳 India',
    segment: 'budget',
    modelCount: 1,
    founded: '1945',
    tagline: 'Connecting Aspirations',
    accentColor: '#00579D',
  },
  {
    id: 'mercedes',
    name: 'Mercedes',
    country: '🇩🇪 Germany',
    segment: 'luxury',
    modelCount: 1,
    founded: '1926',
    tagline: 'The Best or Nothing',
    accentColor: '#C0C0C0',
  },
  {
    id: 'audi',
    name: 'Audi',
    country: '🇩🇪 Germany',
    segment: 'luxury',
    modelCount: 1,
    founded: '1909',
    tagline: 'Vorsprung durch Technik',
    accentColor: '#C0392B',
  },
  {
    id: 'rolls-royce',
    name: 'Rolls-Royce',
    country: '🇬🇧 UK',
    segment: 'luxury',
    modelCount: 1,
    founded: '1906',
    tagline: 'Take the World\'s Stage',
    accentColor: '#C0A020',
  },
  {
    id: 'ferrari',
    name: 'Ferrari',
    country: '🇮🇹 Italy',
    segment: 'sports',
    modelCount: 1,
    founded: '1939',
    tagline: 'We Are the Competition',
    accentColor: '#FF2800',
  },
  {
    id: 'toyota-sports',
    name: 'Toyota GR',
    country: '🇯🇵 Japan',
    segment: 'sports',
    modelCount: 1,
    founded: '1937',
    tagline: 'Gazoo Racing',
    accentColor: '#EB0A1E',
  },
  {
    id: 'volkswagen',
    name: 'Volkswagen',
    country: '🇩🇪 Germany',
    segment: 'premium',
    modelCount: 1,
    founded: '1937',
    tagline: 'Das Auto',
    accentColor: '#001E50',
  },
  {
    id: 'skoda',
    name: 'Skoda',
    country: '🇨🇿 Czech Republic',
    segment: 'premium',
    modelCount: 1,
    founded: '1895',
    tagline: 'Simply Clever',
    accentColor: '#4BA82E',
  },
];
