export interface CarModel {
  id: string;
  name: string;
  brand: string;
  category: 'sedan' | 'suv' | 'luxury' | 'sports';
  img: string;
  engine: string;
  mileage: string;
  price: string;
  seats: number;
  colors: string[];
  description: string;
  topSpeed?: string;
  horsepower?: string;
}

export const cars: CarModel[] = [
  {
    id: 'honda-city',
    name: 'Honda City',
    brand: 'Honda',
    category: 'sedan',
    img: '/cars/Honda City.jpg',
    engine: '1.5L i-VTEC Petrol',
    mileage: '17.8 km/l',
    price: '₹11.5L – ₹15.9L',
    seats: 5,
    topSpeed: '180 km/h',
    horsepower: '121 HP',
    colors: ['#FFFFFF','#C0C0C0','#1a1a1a','#8B0000','#1B4F72'],
    description: 'The Honda City redefines the premium sedan experience with its sleek silhouette, refined 1.5L engine, and a feature-packed cabin that blends luxury with everyday practicality.',
  },
  {
    id: 'mahindra-xuv500',
    name: 'Mahindra XUV 500',
    brand: 'Mahindra',
    category: 'suv',
    img: '/cars/XUV 500.webp',
    engine: '2.2L mHawk Diesel',
    mileage: '16.0 km/l',
    price: '₹13.9L – ₹18.9L',
    seats: 7,
    topSpeed: '175 km/h',
    horsepower: '155 HP',
    colors: ['#1a1a1a','#FFFFFF','#8B6914','#4A235A','#2C3E50'],
    description: 'The XUV 500 commands the road with its bold stance, powerful mHawk diesel engine, and a commanding 7-seat layout — built for those who demand capability without compromise.',
  },
  {
    id: 'merc-c-class',
    name: 'Mercedes C-Class',
    brand: 'Mercedes',
    category: 'luxury',
    img: '/cars/Merc C-Class.jpg',
    engine: '1.5L EQ Boost Mild Hybrid',
    mileage: '14.9 km/l',
    price: '₹55L – ₹73L',
    seats: 5,
    topSpeed: '240 km/h',
    horsepower: '204 HP',
    colors: ['#C0C0C0','#1a1a1a','#FFFFFF','#1B4F72','#4A235A'],
    description: 'An icon reimagined. The C-Class merges cutting-edge MBUX technology with hand-crafted luxury, delivering an unrivalled driving experience that sets the standard for premium sedans.',
  },
  {
    id: 'ferrari-sf90',
    name: 'Ferrari SF90',
    brand: 'Ferrari',
    category: 'sports',
    img: '/cars/SF90.jpg',
    engine: '4.0L Twin-Turbo V8 Hybrid',
    mileage: 'N/A (Track)',
    price: '₹7.5Cr – ₹10Cr',
    seats: 2,
    topSpeed: '340 km/h',
    horsepower: '986 HP',
    colors: ['#CC0000','#FFD700','#1a1a1a','#FFFFFF','#4169E1'],
    description: 'The SF90 Stradale is Ferrari\'s most powerful road car ever — a tri-motor plug-in hybrid that annihilates the 0-100 in 2.5 seconds. Pure Italian engineering at its absolute zenith.',
  },
  {
    id: 'hyundai-verna',
    name: 'Hyundai Verna',
    brand: 'Hyundai',
    category: 'sedan',
    img: '/cars/verna.jpg',
    engine: '1.5L Turbo GDi Petrol',
    mileage: '20.6 km/l',
    price: '₹10.9L – ₹17.4L',
    seats: 5,
    topSpeed: '180 km/h',
    horsepower: '160 HP',
    colors: ['#FFFFFF','#C0C0C0','#1a1a1a','#2196F3','#E91E63'],
    description: 'The all-new Verna arrives with a dramatic fluidic design, a punchy 160HP turbo engine, and a panoramic sunroof — making it the most desirable sedan in its segment.',
  },
  {
    id: 'maruti-ertiga',
    name: 'Maruti Ertiga',
    brand: 'Maruti',
    category: 'suv',
    img: '/cars/ertiga.jpg',
    engine: '1.5L Smart Hybrid',
    mileage: '20.3 km/l',
    price: '₹8.7L – ₹12.9L',
    seats: 7,
    topSpeed: '165 km/h',
    horsepower: '103 HP',
    colors: ['#FFFFFF','#4682B4','#8B4513','#696969','#1a1a1a'],
    description: 'India\'s most versatile family MPV. The Ertiga\'s smart hybrid technology and best-in-class fuel efficiency make it the perfect companion for both city commutes and weekend adventures.',
  },
  {
    id: 'audi-q7',
    name: 'Audi Q7',
    brand: 'Audi',
    category: 'luxury',
    img: '/cars/AudiQ7.jpg',
    engine: '3.0L TFSI V6 Petrol',
    mileage: '12.0 km/l',
    price: '₹88L – ₹1.1Cr',
    seats: 7,
    topSpeed: '250 km/h',
    horsepower: '340 HP',
    colors: ['#1a1a1a','#C0C0C0','#FFFFFF','#8B6914','#2C3E50'],
    description: 'Quattro all-wheel drive meets breathtaking Audi design in the Q7. This 7-seat luxury SUV commands any terrain with 340HP of turbocharged authority and a cabin wrapped in Valcona leather.',
  },
  {
    id: 'toyota-supra',
    name: 'Toyota Supra MK4',
    brand: 'Toyota',
    category: 'sports',
    img: '/cars/supramk4.jpg',
    engine: '3.0L 2JZ-GTE Twin-Turbo',
    mileage: 'N/A (Track)',
    price: '₹45L – ₹85L',
    seats: 2,
    topSpeed: '285 km/h',
    horsepower: '550 HP',
    colors: ['#FF6600','#FFFFFF','#1a1a1a','#FFD700','#CC0000'],
    description: 'A legend reborn. The MK4 Supra\'s 2JZ engine is celebrated as one of the greatest automotive powerplants ever built — capable of legendary tuning potential and raw, unbridled performance.',
  },
  {
    id: 'honda-amaze',
    name: 'Honda Amaze',
    brand: 'Honda',
    category: 'sedan',
    img: '/cars/amaze.jpg',
    engine: '1.2L i-VTEC Petrol',
    mileage: '18.6 km/l',
    price: '₹7.2L – ₹10.5L',
    seats: 5,
    topSpeed: '165 km/h',
    horsepower: '90 HP',
    colors: ['#FFFFFF','#C0C0C0','#1a1a1a','#CC0000','#2196F3'],
    description: 'Big on value, big on comfort. The Honda Amaze packs Honda\'s legendary reliability into an affordable compact sedan with a spacious boot and class-leading fuel economy.',
  },
  {
    id: 'toyota-innova',
    name: 'Toyota Innova Hycross',
    brand: 'Toyota',
    category: 'suv',
    img: '/cars/innova hycross.jpg',
    engine: '2.0L TNGA Hybrid',
    mileage: '21.1 km/l',
    price: '₹19.9L – ₹28.9L',
    seats: 7,
    topSpeed: '170 km/h',
    horsepower: '186 HP',
    colors: ['#FFFFFF','#1a1a1a','#C0C0C0','#8B6914','#2C3E50'],
    description: 'The Innova Hycross elevates the SUV experience with its TNGA platform, strong hybrid powertrain, and a beautifully appointed cabin that seats 7 in absolute comfort.',
  },
  {
    id: 'rolls-royce',
    name: 'Rolls-Royce Ghost',
    brand: 'Rolls-Royce',
    category: 'luxury',
    img: '/cars/rr.jpg',
    engine: '6.75L Twin-Turbo V12',
    mileage: '8.0 km/l',
    price: '₹6.95Cr – ₹8.5Cr',
    seats: 5,
    topSpeed: '250 km/h',
    horsepower: '563 HP',
    colors: ['#C0C0C0','#1a1a1a','#F5F5F0','#1B4F72','#4A235A'],
    description: 'The Rolls-Royce Ghost is the pinnacle of automotive luxury. Every surface is hand-crafted, every journey is orchestrated in silence by 563HP of imperious twin-turbo V12 magnificence.',
  },
  {
    id: 'volkswagen-virtus',
    name: 'Volkswagen Virtus',
    brand: 'Volkswagen',
    category: 'sedan',
    img: '/cars/virtus.jpg',
    engine: '1.5L TSI EVO Petrol',
    mileage: '19.0 km/l',
    price: '₹11.6L – ₹18.9L',
    seats: 5,
    topSpeed: '210 km/h',
    horsepower: '150 HP',
    colors: ['#FFFFFF','#C0C0C0','#1a1a1a','#CC0000','#1B4F72'],
    description: 'German engineering democratised. The Virtus GT brings 150HP of TSI performance to the mainstream sedan market, wrapped in crisp European design that towers above its competition.',
  },
  {
    id: 'hyundai-alcazar',
    name: 'Hyundai Alcazar',
    brand: 'Hyundai',
    category: 'suv',
    img: '/cars/Alcazar.jpg',
    engine: '2.0L MPi Petrol',
    mileage: '14.5 km/l',
    price: '₹16.8L – ₹21.4L',
    seats: 6,
    topSpeed: '175 km/h',
    horsepower: '157 HP',
    colors: ['#FFFFFF','#1a1a1a','#C0C0C0','#8B4513','#2196F3'],
    description: 'The Hyundai Alcazar blends SUV capability with MPV practicality. Its panoramic sunroof, 360° camera, and BOSE sound system redefine what a 6-seater can be.',
  },
  {
    id: 'maruti-ciaz',
    name: 'Maruti Ciaz',
    brand: 'Maruti',
    category: 'sedan',
    img: '/cars/ciaz.jpg',
    engine: '1.5L DualJet Smart Hybrid',
    mileage: '20.65 km/l',
    price: '₹8.9L – ₹12.9L',
    seats: 5,
    topSpeed: '170 km/h',
    horsepower: '103 HP',
    colors: ['#FFFFFF','#C0C0C0','#1a1a1a','#CC0000','#4682B4'],
    description: 'The Ciaz proves that efficiency and elegance aren\'t mutually exclusive. Its smart hybrid system and class-leading boot space make it the pragmatic choice for the discerning sedan buyer.',
  },
  {
    id: 'tata-harrier',
    name: 'Tata Harrier',
    brand: 'Tata',
    category: 'suv',
    img: '/cars/harrier.jpg',
    engine: '2.0L Kryotec Diesel',
    mileage: '16.35 km/l',
    price: '₹15.5L – ₹24.5L',
    seats: 5,
    topSpeed: '180 km/h',
    horsepower: '170 HP',
    colors: ['#1a1a1a','#FFFFFF','#CC0000','#C0C0C0','#2C3E50'],
    description: 'The Tata Harrier is a design statement on wheels. Built on a Land Rover-derived platform, its Kryotec diesel punches hard while the Omega Arc architecture ensures unstoppable capability.',
  },
  {
    id: 'skoda-slavia',
    name: 'Skoda Slavia',
    brand: 'Skoda',
    category: 'sedan',
    img: '/cars/skoda slavia.jpg',
    engine: '1.5L TSI Petrol',
    mileage: '18.7 km/l',
    price: '₹10.9L – ₹17.9L',
    seats: 5,
    topSpeed: '205 km/h',
    horsepower: '150 HP',
    colors: ['#FFFFFF','#C0C0C0','#1a1a1a','#006400','#CC0000'],
    description: 'Czech engineering, Indian soul. The Skoda Slavia delivers a sporty yet refined driving experience, with class-leading safety ratings and a 521-litre boot that defies its compact exterior.',
  },
];
